### ISSUE TITLE
Erroneous example 

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/rules-for-derivatives-lab#1]
The last sentence states that f(x)= 2x^(4) first derivative is f'(x) = 2x^(3). This is incorrect.

"Writing our derivative functions
Let's start by writing a function called find_term_derivative that returns the derivative of a single term. The function takes the derivative of one term represented as a tuple, say  (1,3)(1,3) , and returns its derivative, also represented as a tuple. For example, if the function is  f(x)=2x4f(x)=2x4  so its derivative is  f′(x)=2x3f′(x)=2x3 , then our function find_term_derivative should take an input of (2, 4) and return (2, 3)."

**Comment by alexgriff** [comment]
https://github.com/learn-co-curriculum/rules-for-derivatives-lab/commit/f221987bf262d4197238225a0e570703536a589c
