### ISSUE TITLE
Graphs/plots don't work in derivatives readme and lab

### ISSUE THREAD

**Issue by gmdurante** [learn-co-curriculum/rules-for-derivatives-lab#10]
The plots in the derivatives lessons are throwing errors and not drawing the graphs.  This is true even on the Readme pages that only include the Flatiron content (not labs).  It is making learning via the Bootcamp Prep (and required material for the Technical Interview) difficult.  Furthermore, students have been raising these problems in the "Ask a Question" section of the learn.co platform for at least 4 months.  I think that the issue has also been raised here on Github.  

**Flatiron staff**:  please address the bugs in the derivatives plotting lessons.  Thank you.

**Comment by CristinaTRico** [comment]
I am having this same issue
