### ISSUE TITLE
text error

### ISSUE THREAD

**Issue by miaiseman** [learn-co-curriculum/rules-for-derivatives-lab#13]
I think there's a text error where it says the derivative of f(x)=2x^4 is 2x^3 and the following results you should get... 
"For example, if the function is  f(x)=2x4f(x)=2x4  so its derivative is  f′(x)=2x3f′(x)=2x3 , then our function find_term_derivative should take an input of (2, 4) and return (2, 3)."

**Comment by alexgriff** [comment]
https://github.com/learn-co-curriculum/rules-for-derivatives-lab/commit/f221987bf262d4197238225a0e570703536a589c
