### ISSUE TITLE
Text Error

### ISSUE THREAD

**Issue by ljaden** [learn-co-curriculum/rules-for-derivatives-lab#16]
Writing our derivative functions
Let's start by writing a function called find_term_derivative that returns the derivative of a single term. The function takes the derivative of one term represented as a tuple, say (1,3)(1,3) , and returns its derivative, also represented as a tuple. For example, if the function is f(x)=2x4f(x)=2x4 so its derivative is f′(x)=2x3f′(x)=2x3 , then our function find_term_derivative should take an input of (2, 4) and return (2, 3).

Ive seen a couple of post about this typo and it seem to be fixed but im still have the error on my end. What should i do?

**Comment by mas16** [comment]
Hi ljaden, I'm seeing the corrected value on Learn.co. It should be fixed.
