### ISSUE TITLE
f(x)=2x4  so its derivative is f′(x)=2x3

### ISSUE THREAD

**Issue by AmerSaleemi** [learn-co-curriculum/rules-for-derivatives-lab#17]
I think the derivative should be f'(x) = 4x^3.

Its in the box under Writing our derivative functions.

**Comment by jessepisel** [comment]
Remember that $\frac{d}{dx} x^n = nx^{n-1}$ so $f(x) = 2x^4$ becomes $f'(x) = 8x^3$ which is correct in the lesson. 

I am closing this issue at this time.

**Comment by jessepisel** [comment]
fixed with f221987bf262d4197238225a0e570703536a589c
