### ISSUE TITLE
Mistake in the text for:    f(x)=2x4  so its derivative is  f′(x)=2x3

### ISSUE THREAD

**Issue by benlaird** [learn-co-curriculum/rules-for-derivatives-lab#18]
There's a mistake in this paragraph - f'(x) should be 8x3 and not 2x3

"Let's start by writing a function called find_term_derivative that returns the derivative of a single term. The function takes the derivative of one term represented as a tuple, say  (1,3)(1,3) , and returns its derivative, also represented as a tuple. For example, if the function is  f(x)=2x4   so its derivative is  f′(x)=**2**x3"

**Comment by jessepisel** [comment]
This has been fixed with commit f221987bf262d4197238225a0e570703536a589c.

I am closing this issue at this time.
