### ISSUE TITLE
Incorrect example calculating derivative

### ISSUE THREAD

**Issue by benroyalalexander** [learn-co-curriculum/rules-for-derivatives-lab#19]
In the rules for derivatives lab section of the Math interview prep assessment, there is an error in the example. 

"For example, if the function is  𝑓(𝑥)=2𝑥^4  so its derivative is  𝑓′(𝑥)=2𝑥^3 , then our function find_term_derivative should take an input of (2, 4) and return (2, 3)."

Shouldn't the derivative of 2x^4 be 8x^3?

**Comment by jessepisel** [comment]
This has been fixed with commit f221987bf262d4197238225a0e570703536a589c.

I am closing this issue at this time.
