### ISSUE TITLE
deprecated plotly packages used in last 2 boxes of code

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/rules-for-derivatives-lab#20]

**Comment by kellytdunn** [comment]
I am also getting this error when I try to plot the code in the box with "Def side_by_side_derivative_rules"

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

**Comment by jessepisel** [comment]
Thanks for opening this @kellytdunn :wave:. This has been addressed with 0eeab5746a7073fa034e59f864b8ec00b305fb30 and environment updated [here](https://github.com/learn-co-curriculum/dsc-data-science-env-config/tree/chart_studio_add) I am closing the issue at this time.
