### ISSUE TITLE
Wrong Derivative

### ISSUE THREAD

**Issue by xangorixa** [learn-co-curriculum/rules-for-derivatives-lab#26]
You have the wrong derivative listed in the example prior exercise 1. 

You say that the derivative of F(x)=2x^4 should be f'(x)=2x^3, when it should be F'(x)=8x^3. returning the tuple (8,3).

**Comment by jessepisel** [comment]
This has been fixed with commit f221987bf262d4197238225a0e570703536a589c.

I am closing this issue at this time.
