### ISSUE TITLE
Error in the first example?

### ISSUE THREAD

**Issue by tikhonova** [learn-co-curriculum/rules-for-derivatives-lab#27]
I'm just getting acquainted with the concept, so I'm not 100% positive, but shouldn't the derivative of **𝑓(𝑥)=2𝑥^4** be f'(x) = 2 * 4 * x^3 = **8x^3**?

![image](https://user-images.githubusercontent.com/41370639/88054690-c6f1f780-cb2b-11ea-912a-26045c3b4e0c.png)

**Comment by jessepisel** [comment]
This has been fixed with commit f221987bf262d4197238225a0e570703536a589c.

I am closing this issue at this time.
