### ISSUE TITLE
Typo in the name of the function

### ISSUE THREAD

**Issue by tikhonova** [learn-co-curriculum/rules-for-derivatives-lab#28]
"Ok, now that we have a Python function called **find_derivative*** that can take a derivative of a term, write a function that take as an argument our multi-termed function"

*should be replaced with 'find_term_derivative'

**Comment by jessepisel** [comment]
Thanks for opening this issue @tikhonova :wave:. I have addressed it with commit ed47e6cae22ed73e62f0915288ea7b52e82defb0

I am closing this issue at this time.
