### ISSUE TITLE
Unable to use plotly in the second section of the lab

### ISSUE THREAD

**Issue by tikhonova** [learn-co-curriculum/rules-for-derivatives-lab#29]
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

**Comment by jessepisel** [comment]
Thanks for opening this @tikhonova :wave:. This is a duplicate of #20. Addressed with 0eeab5746a7073fa034e59f864b8ec00b305fb30 and environment updated [here](https://github.com/learn-co-curriculum/dsc-data-science-env-config/tree/chart_studio_add) I am closing the issue at this time.
