### ISSUE TITLE
Typo or bad math?

### ISSUE THREAD

**Issue by SlothDream** [learn-co-curriculum/rules-for-derivatives-lab#3]
"...if the function is  f(x)=2x^4  so its derivative is  f′(x)=2x^3..."

This appears to be a significant typo, or I'm missing something.  My math degree tells me that f' should be 8x^3.

**Comment by annieeby** [comment]
agreed

**Comment by mgavish** [comment]
The fact that there are so many issues gives me pause when thinking about giving this school thousands of dollars to teach something they cant get right themselves.
