### ISSUE TITLE
Yet another lab that has no solution

### ISSUE THREAD

**Issue by AlludedCrabb** [learn-co-curriculum/rules-for-derivatives-lab#5]

**Comment by UpwardTrajectory** [comment]
yeah, I'm getting pretty tired of the mode = 'line' vs mode = 'lines' errors. I feel like they just need to change it once somewhere, or iterate through all their code and just do a find & replace. Sometimes I've been able to find the function from the imported code and fix it, but I'm beginning to talk myself into just skipping it when the source code is flawed.

**Comment by miaiseman** [comment]
Is there a solution somewhere that I can see?
