### ISSUE TITLE
Rules For Derivatives Lab: Writing our derivative functions

### ISSUE THREAD

**Issue by mgavish** [learn-co-curriculum/rules-for-derivatives-lab#9]
Below is a snapshot from the page.  Is f'(x) not equal to 8x^3 and not 2x^3?  

Let's start by writing a function called find_term_derivative that returns the derivative of a single term. The function takes the derivative of one term represented as a tuple, say (1,3)(1,3), and returns its derivative, also represented as a tuple. For example, if the function is f(x)=2x4f(x)=2x4 so its derivative is f′(x)=2x3f′(x)=2x3, then our function find_term_derivative should take an input of (2, 4) and return (2, 3).

**Comment by alexgriff** [comment]
https://github.com/learn-co-curriculum/rules-for-derivatives-lab/commit/f221987bf262d4197238225a0e570703536a589c
